### ISSUE TITLE
Som användare vill jag kunna läsa en policy så att jag vet hur mina personuppgifter behandlas

### ISSUE THREAD

**Issue by EVettainen** [Project-Rika/Rika_WebApp#1]
### **Tasks:**

- [ ] Skapa en sida som innehåller integritetspolicy för webbplatsen
---
- [ ] Policyn förklarar hur data samlas in, lagras och används enligt GDPR
---
- [ ] Ge användarna enkel tillgång till policyn genom länkar i sidfoten och andra relevanta platser
---

### **Acceptanskriterier:**

- [ ] Tydlig tillgång till policyn
- [ ] Sammanfattad och lättförståelig policy
