### ISSUE TITLE
Som en användare vill jag kunna ge eller neka mitt samtyckte till cookies så min integritet respekteras

### ISSUE THREAD

**Issue by EVettainen** [Project-Rika/Rika_WebApp#2]
### **Tasks:**

- [ ] Skapa en cookie-banner som dyker upp vid första besök
---
- [ ] Implementera funktionalitet för att samla in användarens samtyckte till cookies
---
- [ ] Lagra och hantera cookie-samtyckte enligt GDPR
---

### **Acceptanskriterier:**

- [ ] Användare kan acceptera eller neka cookies
- [ ] Cookies sätts endast efter att användaren gett sitt samtyckte
- [ ] Användaren kan när som helst ändra sina cookie inställningar
