### ISSUE TITLE
Som kund vill jag kunna välja mellan olika fraktalternativ så att jag kan välja det alternativ som passar bäst.

### ISSUE THREAD

**Issue by EVettainen** [Project-Rika/Rika_WebApp#3]
### **Tasks:**
- [ ] Skapa integration med PostNord API (eller annan tredjepart) för att hämta tillgängliga fraktalternativ baserat på leveransadress och produktens vikt.
---
- [ ] Dynamiskt uppdatera fraktalternativen och kostnaden i realtid när kundens leveransadress eller produktens vikt ändras.
---
- [ ] Implementera val av fraktalternativ där kunden kan välja det som passar dem bäst.
---
- [ ] Implementera fallback-alternativ om fraktkostnader inte kan hämtas i realtid (t.ex. visa ett standardpris).
---

### **Testfallsbeskrivningar:**

- [ ] Testfall 1: Lyckad hämtning av fraktalternativ

_Förutsättningar:_
- Kunden har lagt till produkter i varukorgen och är i utcheckningsprocessen

_Steg:_
- Kunden har lagt till produkter i varukorgen
- Kunden anger sin leveransadress och går till utcheckning
- Fraktalternativ hämtas från PostNord API baserat på leveransadress och produkt vikt

_Förväntat resultat:_
- Fraktalternativen visas med korrekt kostnad och leveranstid

---

- [ ] Testfall 2: Realtidsuppdatering av fraktkostnad

_Förutsättningar:_
- Kunden ändrar sin leveransadress eller produkterna i varukorgen

_Steg:_
- Ändra leveransadress eller lägg till/ta bort produkter

_Förväntat resultat:_
- Fraktkostnaderna uppdateras dynamiskt i realtid och visas korrekt

---

- [ ] Testfall 3: Felhantering vis misslyckad hämtning av fraktalternativ

_Förutsättningar:_
- Anslutning till PostNord API misslyckas

_Steg:_
- Kund går till utcheckning och försöker hämta fraklatlernativ

_Förväntat resultat:_
- Fallback-alternativ som en standardfrakt visas

---

### **Acceptanskriterier:**

- [ ] Fraktalternativ baserade på plats och vikt
- [ ] Dynamisk uppdatering av fraktkostnader
- [ ] Felhantering
