### ISSUE TITLE
Som en användare vill jag kunna lägga till produkter i varukorgen så att jag kan köpa dom sen

### ISSUE THREAD

**Issue by EVettainen** [Project-Rika/Rika_WebApp#46]
## Tasks
- [ ] Skapa knappar på produktsidan för att välja saker som t.ex. kvantitet, färg, storlek etc.

- [ ] Skapa en knapp på produktsidan för att lägga till en produkt i varukorgen.

- [ ] Skapa en action som går till CartProvider.
     - Vi måste ha en modell/dto att skicka produktinfon till CartProvider. Måste matcha produktmodellen men ha valen med som färg, kvantitet osv.

- [ ] Antalet varor i varukorgen ska synas med ett nummer vid varukorgens icon och uppdateras utan att sidan laddas om

## Acceptanskriterier
_Dessa beskriver när user storyn anses vara klar och uppfyller affärskraven:_ 
   - Användaren kunna lägga till en produkt i sin varukorg. 
   - Varukorgen ska uppdateras i realtid. 

 ## Testfallsbeskrivningar
_Dessa beskriver testfall för att säkerställa att acceptanskriterierna uppfylls._ 

**Testfall 1**: Produkt har lagts till i varukorgen med korrekta värden(kvantitet/färg/storlek)
   - **Förutsättningar**: Användaren klickar på knappen för att lägga till en produkt i sin varukorg. 
   - **Steg**: 
    1. Ange kvantitet/färg/storlek etc på en produkt.
    2. Lägg till produkten i varukorgen. 
   - **Förväntat resultat**: Produkten hamnar i varukorgen med korrekta värden(kvantitet/färg/storlek)

**Testfall 2**: Produkt har **INTE** lagts till i varukorgen pga otillräckligt lager.
   - **Förutsättningar**: Användaren klickar på knappen för att lägga till en produkt i sin varukorg. 
   - **Steg**: 
    1. Ange kvantitet som överstiger lagersaldot på en produkt.
    2. Försöka lägga till produkten i varukorgen. 
   - **Förväntat resultat**: Ett felmeddelande visas som informerar användaren om att det inte finns tillräckligt med produkter i lager, och användaren kan inte lägga produkten i varukorgen.

![Image](https://github.com/user-attachments/assets/bc5a3651-bdb3-49a4-ae89-9b140fca3248)
