### ISSUE TITLE
Som en användare vill jag kunna ta bort saker ur varukorgen så att dom inte är kvar

### ISSUE THREAD

**Issue by EVettainen** [Project-Rika/Rika_WebApp#47]
## Tasks
- [ ] Skapa en ta bort knapp för varje separat produkt

- [ ]  Skapa en knapp för att ångra senaste borttagningen
  - Ska inte synas förens man tagit bort något.

- [ ] Skapa en action som går till CartProvider.
     - Ska tas bort ur databasen om användaren är inloggad
     - Ta bort från cookie/local storage/session?
     - Hantera statuskoden/meddelandet som man får tillbaka av CartProvider.

## Acceptanskriterier
_Dessa beskriver när user storyn anses vara klar och uppfyller affärskraven:_ 
   - Användaren ska kunna ta bort en produkt från varukorgen. 
   - Hantera statuskoden/meddelandet som man får tillbaka från CartProvider 

 ## Testfallsbeskrivningar
_Dessa beskriver testfall för att säkerställa att acceptanskriterierna uppfylls._ 

**Testfall 1**: Lyckad borttagning av produkt 
   - **Förutsättningar**: Det finns minst en produkt i varukorgen.
   - **Steg**: 
    1. Användaren tar bort en produkt ur varukorgen. 
    2.  Vi får tillbaka ett 200 ok av CartProvider
   - **Förväntat resultat**: Användaren lyckas ta bort en produkt ur sin varukorg

**Testfall 2**: Produkt har **INTE** lyckats tas bort ur varukorgen.
   - **Förutsättningar**: Det finns minst en produkt i varukorgen.
   - **Steg**: 
    1.  Användaren tar bort en produkt ur varukorgen. 
    2.  Vi får inte 200 ok tillbaka av CartProvider
   - **Förväntat resultat**: Ett felmeddelande visar att det inte gick att ta bort produkten ur varukorgen

![Image](https://github.com/user-attachments/assets/f2a8a484-8f07-4264-9a9d-11e94f5530d9)
