### ISSUE TITLE
Som en kund vill jag kunna betala med kreditkort

### ISSUE THREAD

**Issue by EVettainen** [Project-Rika/Rika_WebApp#5]
![Image](https://github.com/user-attachments/assets/6237c02e-c102-4827-8801-78c9e1d0d8d1)
# Tasks

 - [ ] **Task 1: Implementera UI för betalning med kreditkort**
   - Designa ett formulär där en kund kan ange sitt namn, kortnummer, utgångsdatum och CVC.

 - [ ] **Task 2: Implementera Stripe Elements (förbyggda Stripe-komponenter) för kreditkort**
   - Använd Stripe Elements för att validera kortinformationen på ett säkert sätt.

- [ ] **Task 3: Skapa betalningslogiken**
   - Skicka en betalningsbegäran till Stripe API och hantera statusmeddelandet som kommer tillbaka från API:et.

- [ ] **Task 4: Hantera betalningsbekräftelse**
   - Skapa logik för lyckad eller misslyckad betalning. Om betalningen gått igenom så omdirigera till orderbekräftelsesidan, annars visa felmeddelande.

- [ ] **Task 5: Implementera funktionalitet för orderbekräftelse via email**
   - Anropa EmailProvider API:et för att skicka ut ett mail med orderbekräftelse till kunden.

## Acceptanskriterier
   1. En kund ska kunna ange sina kortuppgifter i ett säkert formulär
   2. Efter validering, när kunden trycker på betala-knappen ska en betalningsförfrågan skickas till Stripe med kortuppgifterna.
   3. Vid lyckad betalning ska kunden omdirigeras till en sida för orderbekräftelse.
   4. Vid lyckad betalning ska kunden få en orderbekräftelse skickad till sin email.
   5. Vid misslyckad betalning ska kunden få ett felmeddelande om varför betalningen ej gick igenom.

## Testfallsbeskrivningar

- [ ] **Testfall 1: Lyckad betalning med kortuppgifter**
   - Förutsättningar: Kunden har saker i sin kundkorg och har valt att betala med kort. 
   - Steg:
       1. Navigera till kassan och välj betalning med kort. 
       2. Fyll i kortuppgifter (kortinnehavarens namn, kortnummer, utgångsdatum, CVC).
       3. Klicka på "Betala"-knappen.

   - Förväntat resultat: Betalningen går igenom och kunden blir omdirigerad till sidan för orderbekräftelse och får ett Email skickat med orderbekräftelse till sin email.
