### ISSUE TITLE
Som en användare vill jag kunna filtrera i produktkatalogen för att hitta specifika produkter

### ISSUE THREAD

**Issue by EVettainen** [Project-Rika/Rika_WebApp#52]
## Tasks
- [ ] Filtrera utifrån kategori
- [ ] Filtrera utifrån märken
- [ ] Filtrera utifrån storlek
- [ ] Filtrera utifrån färg
- [ ] Filtrera utifrån pris
- [ ] Filtrera utifrån reapris
- [ ] Filtrera utifrån material
- [ ] Filtrera utifrån årstid

## Acceptanskriterier
_Dessa beskriver när user storyn anses vara klar och uppfyller affärskraven:_ 
   - Korrekt filtrering.
   - Kombinering av filter.
   - Dynamisk uppdatering.
   - Hantera inga träffar.
   - Återställ filter.

 ## Testfallsbeskrivningar
_Dessa beskriver testfall för att säkerställa att acceptanskriterierna uppfylls._ 

**Testfall 1**: Lyckad filtrering efter kategori
   - **Förutsättningar**: Databasen innehåller produkter i olika kategorier.
   - **Steg**: Välj ett specifikt filter, såsom en viss kategori.
   - **Förväntat resultat**: Endast produkter som tillhör den valda kategorin visas i resultaten.

**Testfall 2**: Lyckad filtrering med flera filter
   - **Förutsättningar**: Produkter i databasen har olika storlekar, färger och märken.
   - **Steg**: Välj flera filter, såsom kategori, märke och färg.
   - **Förväntat resultat**: Endast produkter som matchar alla valda filter visas i resultaten.

**Testfall 3**: Lyckad filtrering på prisintervall
   - **Förutsättningar**: Produkter i databasen har varierande priser.
   - **Steg**: Ange ett minimum- och maximumpris.
   - **Förväntat resultat**:  Endast produkter inom det valda prisintervallet visas.

**Testfall 4**:  Filtrering med flera filter misslyckas
   - **Förutsättningar**: Produkter i databasen har olika storlekar, färger och märken.
   - **Steg**: Användaren väljer flera filter, såsom "Kategori: Kläder", "Märke: Nike" och "Färg: Röd".
   - **Förväntat resultat**:  Endast produkter som matchar alla valda filter ska visas i resultaten.
   - **Faktiskt resultat**: Produkterna som visas uppfyller inte alla filterkrav, till exempel visas även 
        produkter med andra märken än "Nike" eller andra färger än "Röd".

![Image](https://github.com/user-attachments/assets/881dfca2-b721-441e-b1c1-824907cf8b0a)
