### ISSUE TITLE
Som en användare vill jag kunna sortera bland produkter så dom hamnar efter önskad ordning

### ISSUE THREAD

**Issue by EVettainen** [Project-Rika/Rika_WebApp#53]
## Tasks
- [ ] Sortera utifrån högt/lågt pris
- [ ] Sortera utifrån betyg
- [ ] Sortera utifrån senast inkommit/datum

## Acceptanskriterier
_Dessa beskriver när user storyn anses vara klar och uppfyller affärskraven:_ 
   - Det ska gå att sortera produkterna efter de sorteringsalternativ vi skrivit tasks.

 ## Testfallsbeskrivningar
_Dessa beskriver testfall för att säkerställa att acceptanskriterierna uppfylls._ 

**Testfall 1**: Vi lyckas sortera produkterna utifrån angivna kriterier
   - **Förutsättningar**: Det finns produkter
   - **Steg**: 
    1. Välja kriterier att sortera efter 
    2. Uppdatera gränssnittet för att visa produkterna i rätt ordning
   - **Förväntat resultat**: Produkterna visas i rätt ordning efter valt kriterie.

**Testfall 2**: Vi lyckas INTE sortera produkterna utifrån angivna kriterier
   - **Förutsättningar**: Det finns produkter
   - **Steg**: 
    1. Välja kriterier att sortera efter 
    2. Försök uppdatera gränssnittet för att visa produkterna i rätt ordning
   - **Förväntat resultat**: Produkterna visas INTE i rätt ordning efter valt kriterie.

![Image](https://github.com/user-attachments/assets/e1d910de-be5f-4ca2-a1b9-1897f0323b60)
